### ISSUE TITLE
get WebACL for group from server

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#2]
requires #1

- [ ] function performs a GET for the ACL on a group (which is a BasicContainer one level down from BaseContainer. (#26, #18 for root container, #23 for group container)
- [x] function parses an ACL file (npm package `jsonacl` may be useful, or `jq` if it isn't ...) into appropriate objects)
- [x] function outputs (to the console) the webIDs in the ACL file for the group, and their permissions, in a table format.  (npm package `clui` can draw command-line tables)   OR may punt on pretty output until #4.

**Comment by jermnelson** [comment]
Should consider [N3](https://www.npmjs.com/package/n3) for parsing and displaying the permissions if ACL is in RDF.

**Comment by ndushay** [comment]
remaining work is ticketed in more atomic issues, so closing this one.
