### ISSUE TITLE
way to POST webACL ttl to root, /repository or group container

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#25]
required by #19
requires to #5

We will want tests to show
- what happens when POST works
   - correct HTTP return codes
   - prove that webACL afterwards matches what was POSTed (and that webACL before did *not* match webACL we will write)
- what happens when POST doesn't work
  -  group doesn't exist
  - request doesn't go thru
  - webid isn't authorized
- works for root container
- works for group container

It is okay if this is split into separate issues / functions / test classes for root vs group container ...

### auth/auth concerns

See #5

Note that in production, we will need to use a real webid string and use JWT to pass accessToken to cognito;  it is possible this is figured out in LD4P/sinopia_server#77.   If there is no straightforward way to do this yet, we could use basic auth and cmharlow webid as admin user for now, and split this into separate ticket.

Note that we probably want Michelle *and* the devs with admin access (as default config setting)

**Comment by ndushay** [comment]
See sinopia_client?

See LD4P/sinopia_editor#420 - Mike's work on `src/loadTemplatesjs` uses superagent.

**Comment by ndushay** [comment]
@mjgiarlo I believe this is done now via your script?  wanna close it?

**Comment by mjgiarlo** [comment]
@ndushay good eye! Yes. Closing.
