### ISSUE TITLE
create CLI for sinopia_acl

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#4]
We want a CLI where the admin user can:

(so far)
- specify a group and see comprehensible results of which webIDs are in the group on the server and what permissions each has.  (requires #2)
- specify a group and a webID to add and see comprehensible results showing that the webID was added. (requires #3) ... could be done as a separate ticket.

npm modules such as `cli`, `minimist` (for options parsing), `clui` (for table output) may be useful

**Comment by ndushay** [comment]
Note - we are doing "all or none" as our permissions, so this simplifies to lists of userids, not tables with permissions.

**Comment by ndushay** [comment]
See LD4P/sinopia_server#42 for CLI functionality (esp towards bottom)

**Comment by ndushay** [comment]
In #8, Jeremy indicates the command line arguments are avail:

>We'll have access to the process.argv that allow a CLI call like `node src/index.js username group-id`

I would also offer the suggestion of npm scripts, so we hopefully have less typing for Michelle:
- `npm run addUser groupContainerName userId`
- `npm run removeUser groupContainerName userId`

and possibly
- `npm run listUsers groupContainerName`

**Comment by mjgiarlo** [comment]
Authentication is out of scope for this issue. That is ticketed in #17 for follow-on work.
