### ISSUE TITLE
cognito:  send only one confirmation email (instead of 4) when someone signs up for cognito

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#57]
Our current ACL approach depends on having a way of knowing who is signing up for a cognito account.  This may be set up in terraform already, but @michelleif is not getting emails (for dev).

Definitely want to get emails for prod, and possibly for stage as well. 

- [x] can the email subject distinguish between prod, stage and dev environment? (unchecking this because the email subject does not say what environment it's coming from)
- [x] use sinopia_admin@stanford.edu as email ~~@michelleif's call:  should these emails go to a list?  Seems like a bad "truck factor" situation if they only go to your personal email.~~
- [x] text of emails ok
- [x] subject of emails ok
- [x] works on dev
- [x] works on test
- [x] works on prod

**Comment by michelleif** [comment]
have emails go to sinopia_admin@stanford.edu

**Comment by rsmith11** [comment]
Is sinopia_admin@stanford.edu an email list?  Typically email lists created by the campus mailman service include an @lists.stanford.edu in the name.

**Comment by rsmith11** [comment]
Thanks for the clarification.  I'll be sending an email verification from Amazon AWS SES service shortly to confirm that email address.  Once it's confirmed, then I can configure AWS to send email from that email address.

**Comment by rsmith11** [comment]
I just made some changes in development and did a test user creation.  Let me know if you did or didn't receive an email confirmation.

**Comment by michelleif** [comment]
I got the email but it says "Please add them to the necessary group in Trellis." We decided that I don't need to add users to groups in Trellis right? The email is just for informational purposes?

**Comment by rsmith11** [comment]
That is some old text that I wrote up.  If you'd like it changed, let me know what you want it changed to then I'll update the Lambda code that sends it.

**Comment by michelleif** [comment]
the text of the email has been revised by https://github.com/LD4P/sinopia/issues/203

why is "can the email subject distinguish between prod, stage and dev environment?" checked off? the email I get from PRD and from DEV just says "Sinopia User Registration". No indication of environment.

**Comment by michelleif** [comment]
bug: I get 4 separate (but identical) confirmation emails (instead of one) sent to me at the same time when a user creates a new account on PRD.
I get 3 separate (but identical) confirmation emails (instead of one) sent to me at the same time when a user creates a new account on DEV.

**Comment by michelleif** [comment]
we decided this is future technical debt and not important for M3

**Comment by michelleif** [comment]
I am only receiving one email now. closing.
