### ISSUE TITLE
populateEmptyTrellis gets username and password from ENV vars; config tweaks

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#63]
Description: get past hardcoded usernames in the scripts and address config information being set in environment vars by terraform for deployments to AWS (dev, stage, prod).

- [x] Convert config values to get things from `process.env.XXX` or `config.util.getEnv(xxx)`, thus avoiding the need for NODE_ENV var (run locally with command line ENV vars, run remotely with ENV vars set by terraform)

- [x] Script needs cognito username and password to get JWT cognito access token 

- [x] Script needs aws_access_key_id and aws_secret_access_key to get webid using AWS SDK.

- [x] populateEmptyTrellis and WebAccessControl ... currently hardcoded for adminUserWebIds()

- docker will update the image
- [ ] npm package will need to be updated

- [ ] possibly be more intentional about how sinopia_editor, sinopia_server, sinopia_indexing_pipeline get the correct code.

Requires #56

**Comment by ndushay** [comment]
related to #65

**Comment by ndushay** [comment]
@mjgiarlo I'm not even sure how to address the remaining two things ... should we:
- make separate tickets for them
- deal with them and then close this ticket
- some of each?
- other?

**Comment by mjgiarlo** [comment]
@ndushay I'll give them a shot now.

**Comment by mjgiarlo** [comment]
@ndushay Here's what I did:

* Bumped sinopia_acl to 0.2.0: https://github.com/LD4P/sinopia_acl/blob/0745f552b6d87ad85381a3b2972e14c03791dad3/package.json#L3
* Published the package: https://www.npmjs.com/package/sinopia_acl
* Built and pushed an updated docker image w/ the following tags: [0, 0.2, 0.2.0, and latest](https://hub.docker.com/r/ld4p/sinopia_acl/tags)
* Pointed [sinopia_editor](https://github.com/LD4P/sinopia_editor/pull/470) and [sinopia_server](https://github.com/LD4P/sinopia_server/pull/95) at 0.2 tag of sinopia_acl image

Does that wrap things up?

**Comment by ndushay** [comment]
@mjgiarlo  Thanks!

i'm closing this ticket.  Dunno if you need to do anything for sinopia_pipeline code, but if so you can ticket work in that project.  Any remaining M3 work will bubble up from remaining open tix on this milestone.

**Comment by mjgiarlo** [comment]
@ndushay nope! pipeline does not use ACL. thanks!
