### ISSUE TITLE
ENV vars and ???  in AWS setup for sinopia_acl

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#65]
I believe we will need these, obviously configured per appropriate environment (dev, stage, prod):

- TRELLIS_BASE_URL
    - let me know if you are including https://  or not (assuming yes)
- for cognito JWT to create containers:
    - COGNITO_ADMIN_USER
    - COGNITO_ADMIN_PASSWORD
- for AWS SDK to get webid from username in pool:
    - AWS_ACCESS_KEY_ID (user with approp permissions)
    - AWS_SECRET_ACCESS_KEY (user with approp permissions)
    - AWS_REGION
    - AWS_COGNITO_DOMAIN
        - could be just COGNITO_DOMAIN … but keep it consistent with other Sinopia containers, I guess?
        - let me know if you are including https://  or not (assuming no)
    - COGNITO_CLIENT_ID
    - COGNITO_USER_POOL_ID

(for reference: ENV vars for editor container:  LD4P/sinopia_editor#458)

**Comment by ndushay** [comment]
tagging @mjgiarlo so he can chime in with any stuff he is aware of.

**Comment by mjgiarlo** [comment]
See also https://github.com/LD4P/sinopia_editor/pull/462

**Comment by ndushay** [comment]
These vars are now "definite", per PR #66.

**Comment by rsmith11** [comment]
I don't know what the password is for the `sinopia_client-dev-tester` user in Cognito.  If somebody could slack that to me that would be great.

**Comment by mjgiarlo** [comment]
@rsmith11 :speech_balloon: 
> I don't know what the password is for the `sinopia_client-dev-tester` user in Cognito. If somebody could slack that to me that would be great.

https://github.com/sul-dlss/shared_configs/blob/sinopia-dev/README.md

**Comment by mjgiarlo** [comment]
Here is an unresolved ENV var question that is currently blocking a PR:

https://github.com/LD4P/sinopia_server/pull/100#discussion_r279206126

**Comment by mjgiarlo** [comment]
@rsmith11 @ndushay @jermnelson Do we think this is done? I'm wondering if we should close this issue and, if changes are needed as we discover bugs, ticket those separately.

**Comment by mjgiarlo** [comment]
@rsmith11 What say you about :point_up: ?
