### ISSUE TITLE
Retrieve Profiles from Github and persist resource templates to sinopia_server

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_acl#77]
Use github api to retrieve a set of profiles and persist the resource templates to trellis.

**Comment by michelleif** [comment]
@jermnelson does 3.1.0 fix this?

**Comment by jermnelson** [comment]
> @jermnelson does 3.1.0 fix this?

Version `3.1.0` does not use the code in `sinopia_acl` so I think we can close this issue.
